# Mašinų dalys, retumai, komandų bazės, lenktynių padangos (be pygame).

RARITY_STEPS = [
    ("Common", (120, 120, 120), 9),
    ("Uncommon", (70, 180, 70), 16),
    ("Rare", (60, 120, 255), 30),
    ("Epic", (160, 80, 220), 45),
    ("Legendary", (255, 200, 60), 70),
    ("Beast", (138, 3, 3), None),
]
CAR_PARTS = [
    "Front Wing",
    "Brakes",
    "Suspension",
    "Rear Wing",
    "Gearbox",
    "Engine",
    "Battery",
]
MAX_CAR_TIER = len(RARITY_STEPS) - 1
# Kiekviena dalis: Common = 0 bonus, Beast (5) = pilni bonusai; pit indėlis 1.00s → sumažėja iki (1 - pit_saved_at_max).
PART_UPGRADE_CURVES = {
    "Front Wing": {
        "speed": 41,
        "cornering": 14,
        "power_unit": 15,
        "qualifying": 16,
        "overtake": 0,
        "pit_saved_at_max": 0.49,
    },
    "Gearbox": {
        "speed": 16,
        "cornering": 13,
        "power_unit": 37,
        "qualifying": 13,
        "overtake": 0,
        "pit_saved_at_max": 0.56,
    },
    "Engine": {
        "speed": 15,
        "cornering": 38,
        "power_unit": 14,
        "qualifying": 13,
        "overtake": 0,
        "pit_saved_at_max": 0.48,
    },
    "Battery": {
        "speed": 10,
        "cornering": 15,
        "power_unit": 8,
        "qualifying": 9,
        "overtake": 31,
        "pit_saved_at_max": 0.31,
    },
    "Brakes": {
        "speed": 13,
        "cornering": 41,
        "power_unit": 17,
        "qualifying": 14,
        "overtake": 0,
        "pit_saved_at_max": 0.52,
    },
    "Rear Wing": {
        "speed": 13,
        "cornering": 15,
        "power_unit": 41,
        "qualifying": 16,
        "overtake": 0,
        "pit_saved_at_max": 0.49,
    },
    "Suspension": {
        "speed": 38,
        "cornering": 12,
        "power_unit": 15,
        "qualifying": 13,
        "overtake": 0,
        "pit_saved_at_max": 0.56,
    },
}
# 2025 sezono komandų bazinės mašinos (7 dalys, kaip Car Development). Žaidėjas vėliau keičia savo kopiją per profilį.
TEAM_CAR_BASE_PARTS = {
    "Red Bull": {
        "Engine": 5,
        "Battery": 4,
        "Front Wing": 4,
        "Rear Wing": 4,
        "Suspension": 4,
        "Brakes": 4,
        "Gearbox": 4,
    },
    "McLaren": {
        "Engine": 4,
        "Battery": 4,
        "Front Wing": 4,
        "Rear Wing": 4,
        "Suspension": 4,
        "Brakes": 4,
        "Gearbox": 4,
    },
    "Ferrari": {
        "Engine": 4,
        "Battery": 4,
        "Front Wing": 4,
        "Rear Wing": 4,
        "Suspension": 4,
        "Brakes": 3,
        "Gearbox": 4,
    },
    "Mercedes": {
        "Engine": 4,
        "Battery": 3,
        "Front Wing": 3,
        "Rear Wing": 4,
        "Suspension": 4,
        "Brakes": 3,
        "Gearbox": 3,
    },
    "Aston Martin": {
        "Engine": 3,
        "Battery": 3,
        "Front Wing": 3,
        "Rear Wing": 3,
        "Suspension": 3,
        "Brakes": 3,
        "Gearbox": 3,
    },
    "Alpine": {
        "Engine": 3,
        "Battery": 2,
        "Front Wing": 3,
        "Rear Wing": 3,
        "Suspension": 3,
        "Brakes": 3,
        "Gearbox": 3,
    },
    "VCARB": {
        "Engine": 3,
        "Battery": 2,
        "Front Wing": 2,
        "Rear Wing": 2,
        "Suspension": 3,
        "Brakes": 2,
        "Gearbox": 3,
    },
    "Williams": {
        "Engine": 2,
        "Battery": 2,
        "Front Wing": 3,
        "Rear Wing": 2,
        "Suspension": 2,
        "Brakes": 2,
        "Gearbox": 2,
    },
    "Sauber": {
        "Engine": 2,
        "Battery": 2,
        "Front Wing": 2,
        "Rear Wing": 2,
        "Suspension": 3,
        "Brakes": 2,
        "Gearbox": 2,
    },
    "Haas": {
        "Engine": 2,
        "Battery": 2,
        "Front Wing": 2,
        "Rear Wing": 2,
        "Suspension": 2,
        "Brakes": 2,
        "Gearbox": 2,
    },
}
TEAM_ABBREV = {
    "Red Bull": "RBR",
    "Ferrari": "FER",
    "McLaren": "MCL",
    "Mercedes": "MER",
    "Aston Martin": "AMR",
    "Alpine": "ALP",
    "VCARB": "VAR",
    "Haas": "HAA",
    "Williams": "WIL",
    "Sauber": "SAU",
}

# Lenktynių padangų simuliacijos lentelė (naudoja pagrindinis žaidimo modulis).
RACE_TYRE_COMPOUNDS = {
    "SOFT": {
        "pace": 1.035,
        "wear_laps": 3,
        "color": (230, 60, 60),
        "comment": "Fastest pace, but drops after ~3 laps.",
    },
    "MEDIUM": {
        "pace": 1.0,
        "wear_laps": 4,
        "color": (236, 206, 56),
        "comment": "Balanced speed and life, good all-round choice.",
    },
    "HARD": {
        "pace": 0.972,
        "wear_laps": 5,
        "color": (236, 236, 236),
        "comment": "Slower, but stable for longer stints.",
    },
    "INTER": {
        "pace": 0.955,
        "wear_laps": 4,
        "color": (72, 192, 96),
        "comment": "For mixed/wet track, safer in damp conditions.",
    },
    "WET": {
        "pace": 0.92,
        "wear_laps": 5,
        "color": (68, 120, 236),
        "comment": "Heavy rain tyre, best grip in standing water.",
    },
}
