# Statiniai F1 žaidimo duomenys (komandos, vairuotojai, atnaujinimų sąrašas).
# Kanoninis šaltinis pakete f1_game; šaknies game_data.py tik perexportuoja.
# Šį modulį galima importuoti be pygame — patogu testams ir refaktoriui.

# --- F1 KOMANDOS IR SVORIAI ---
F1_TEAMS = [
    {"name": "Red Bull", "color": (0, 0, 128), "weight": 2},
    {"name": "Ferrari", "color": (255, 0, 0), "weight": 2},
    {"name": "McLaren", "color": (255, 165, 0), "weight": 4},
    {"name": "Mercedes", "color": (0, 160, 160), "weight": 4},
    {"name": "Aston Martin", "color": (0, 100, 80), "weight": 10},
    {"name": "Alpine", "color": (0, 128, 255), "weight": 12},
    {"name": "VCARB", "color": (100, 100, 255), "weight": 14},
    {"name": "Haas", "color": (255, 255, 255), "weight": 16},
    {"name": "Williams", "color": (0, 80, 255), "weight": 18},
    {"name": "Sauber", "color": (0, 255, 0), "weight": 20},
]
TOTAL_WEIGHT = sum(t["weight"] for t in F1_TEAMS)
TEAM_DRIVERS_2025 = {
    "Red Bull": ["Max Verstappen", "Yuki Tsunoda"],
    "Ferrari": ["Charles Leclerc", "Lewis Hamilton"],
    "McLaren": ["Lando Norris", "Oscar Piastri"],
    "Mercedes": ["George Russell", "Kimi Antonelli"],
    "Aston Martin": ["Fernando Alonso", "Lance Stroll"],
    "Alpine": ["Pierre Gasly", "Jack Doohan"],
    "VCARB": ["Liam Lawson", "Isack Hadjar"],
    "Haas": ["Esteban Ocon", "Oliver Bearman"],
    "Williams": ["Alex Albon", "Carlos Sainz"],
    "Sauber": ["Nico Hulkenberg", "Gabriel Bortoleto"],
}
DRIVER_COUNTRY = {
    "Max Verstappen": "Netherlands",
    "Yuki Tsunoda": "Japan",
    "Charles Leclerc": "Monaco",
    "Lewis Hamilton": "United Kingdom",
    "Lando Norris": "United Kingdom",
    "Oscar Piastri": "Australia",
    "George Russell": "United Kingdom",
    "Kimi Antonelli": "Italy",
    "Fernando Alonso": "Spain",
    "Lance Stroll": "Canada",
    "Pierre Gasly": "France",
    "Jack Doohan": "Australia",
    "Liam Lawson": "New Zealand",
    "Isack Hadjar": "France",
    "Esteban Ocon": "France",
    "Oliver Bearman": "United Kingdom",
    "Alex Albon": "Thailand",
    "Carlos Sainz": "Spain",
    "Nico Hulkenberg": "Germany",
    "Gabriel Bortoleto": "Brazil",
}
DRIVER_NUMBERS_2025 = {
    "Max Verstappen": 1,
    "Yuki Tsunoda": 22,
    "Charles Leclerc": 16,
    "Lewis Hamilton": 44,
    "Lando Norris": 4,
    "Oscar Piastri": 81,
    "George Russell": 63,
    "Kimi Antonelli": 12,
    "Fernando Alonso": 14,
    "Lance Stroll": 18,
    "Pierre Gasly": 10,
    "Jack Doohan": 7,
    "Liam Lawson": 30,
    "Isack Hadjar": 6,
    "Esteban Ocon": 31,
    "Oliver Bearman": 87,
    "Alex Albon": 23,
    "Carlos Sainz": 55,
    "Nico Hulkenberg": 27,
    "Gabriel Bortoleto": 5,
}
AI_DRIVER_NUMBERS = set(int(v) for v in DRIVER_NUMBERS_2025.values())
# Stat values 1–20 (same categories as driver upgrades)
DRIVER_STATS = {
    "Max Verstappen": {
        "Overtaking": 20,
        "Defending": 19,
        "Qualifying": 20,
        "Race Start": 19,
        "Tyre Management": 19,
    },
    "Lando Norris": {
        "Overtaking": 18,
        "Defending": 17,
        "Qualifying": 18,
        "Race Start": 17,
        "Tyre Management": 17,
    },
    "Charles Leclerc": {
        "Overtaking": 17,
        "Defending": 16,
        "Qualifying": 19,
        "Race Start": 16,
        "Tyre Management": 16,
    },
    "Oscar Piastri": {
        "Overtaking": 17,
        "Defending": 16,
        "Qualifying": 17,
        "Race Start": 17,
        "Tyre Management": 17,
    },
    "Lewis Hamilton": {
        "Overtaking": 17,
        "Defending": 17,
        "Qualifying": 17,
        "Race Start": 16,
        "Tyre Management": 18,
    },
    "George Russell": {
        "Overtaking": 16,
        "Defending": 16,
        "Qualifying": 17,
        "Race Start": 16,
        "Tyre Management": 16,
    },
    "Carlos Sainz": {
        "Overtaking": 16,
        "Defending": 15,
        "Qualifying": 16,
        "Race Start": 16,
        "Tyre Management": 16,
    },
    "Fernando Alonso": {
        "Overtaking": 16,
        "Defending": 17,
        "Qualifying": 16,
        "Race Start": 15,
        "Tyre Management": 17,
    },
    "Alex Albon": {
        "Overtaking": 14,
        "Defending": 14,
        "Qualifying": 14,
        "Race Start": 13,
        "Tyre Management": 14,
    },
    "Pierre Gasly": {
        "Overtaking": 14,
        "Defending": 13,
        "Qualifying": 14,
        "Race Start": 13,
        "Tyre Management": 14,
    },
    "Esteban Ocon": {
        "Overtaking": 13,
        "Defending": 14,
        "Qualifying": 13,
        "Race Start": 13,
        "Tyre Management": 13,
    },
    "Nico Hulkenberg": {
        "Overtaking": 13,
        "Defending": 13,
        "Qualifying": 13,
        "Race Start": 12,
        "Tyre Management": 14,
    },
    "Yuki Tsunoda": {
        "Overtaking": 14,
        "Defending": 13,
        "Qualifying": 14,
        "Race Start": 14,
        "Tyre Management": 12,
    },
    "Lance Stroll": {
        "Overtaking": 11,
        "Defending": 11,
        "Qualifying": 10,
        "Race Start": 11,
        "Tyre Management": 11,
    },
    "Liam Lawson": {
        "Overtaking": 12,
        "Defending": 11,
        "Qualifying": 12,
        "Race Start": 12,
        "Tyre Management": 11,
    },
    "Isack Hadjar": {
        "Overtaking": 11,
        "Defending": 10,
        "Qualifying": 11,
        "Race Start": 11,
        "Tyre Management": 10,
    },
    "Oliver Bearman": {
        "Overtaking": 11,
        "Defending": 11,
        "Qualifying": 11,
        "Race Start": 11,
        "Tyre Management": 11,
    },
    "Jack Doohan": {
        "Overtaking": 10,
        "Defending": 10,
        "Qualifying": 10,
        "Race Start": 10,
        "Tyre Management": 10,
    },
    "Kimi Antonelli": {
        "Overtaking": 12,
        "Defending": 11,
        "Qualifying": 13,
        "Race Start": 12,
        "Tyre Management": 11,
    },
    "Gabriel Bortoleto": {
        "Overtaking": 10,
        "Defending": 9,
        "Qualifying": 10,
        "Race Start": 10,
        "Tyre Management": 9,
    },
}
# 2025 sezono rikiuotė / forma (0.35–1.0): stipresni vairuotojai → geresnė „fabrikinė“ mašina ir didesnis lenktynių tempas nei pradedančiajam žaidėjui su Common dalimis.
DRIVER_2025_STRENGTH = {
    "Max Verstappen": 0.99,
    "Lando Norris": 0.93,
    "Oscar Piastri": 0.91,
    "Charles Leclerc": 0.88,
    "George Russell": 0.86,
    "Lewis Hamilton": 0.84,
    "Carlos Sainz": 0.82,
    "Kimi Antonelli": 0.78,
    "Fernando Alonso": 0.74,
    "Alex Albon": 0.70,
    "Pierre Gasly": 0.67,
    "Yuki Tsunoda": 0.65,
    "Esteban Ocon": 0.63,
    "Oliver Bearman": 0.61,
    "Liam Lawson": 0.59,
    "Nico Hulkenberg": 0.55,
    "Isack Hadjar": 0.53,
    "Gabriel Bortoleto": 0.51,
    "Lance Stroll": 0.44,
    "Jack Doohan": 0.42,
}
UPGRADE_POOL = [
    "Overtaking Upgrade",
    "Defending Upgrade",
    "Qualifying Upgrade",
    "Race Start Upgrade",
    "Tyre Management Upgrade",
]
