# Sezono Grand Prix kalendorius (statiniai duomenys).
SEASON_GP_CALENDAR = [
    {
        "short_lt": "Brazilija",
        "short_en": "Brazil",
        "venue_lt": "Brazilija, São Paulo",
        "circuit_lt": "Interlagos (Autódromo J. C. Pace)",
        "title_hud": "AUTODROMO JOSE CARLOS PACE",
        "subtitle_hud": "São Paulo — Brazil",
        "air_c": 28,
        "track_c": 52,
        "race_laps": 71,
        "air_condition_lt": "Debesuota, vietomis perkūnija",
        "humidity_pct": 78,
        "wind_ms": "3–5",
        "wind_dir_lt": "Šiaurės rytai (NE)",
        "venue_en": "São Paulo, Brazil",
        "circuit_en": "Interlagos (Autódromo José Carlos Pace)",
        "air_condition_en": "Humid subtropical, cloudy, afternoon storms possible",
        "wind_dir_en": "Northeast",
        "weather_lines_lt": [
            "Drėgna subtropinė: debesuota, lūžtančios perkūnijos tikimybė ~40%.",
            "Drėgmė ~78 %, vėjas ~3 m/s (šiaurės rytai).",
            "Dangos temperatūra aukšta po saulės — padangos greitai „įšyla“.",
        ],
        "track_transform": {
            "scale_x": 1.0,
            "scale_y": 1.0,
            "shift_x": 0.0,
            "shift_y": 0.0,
            "rotate_deg": 0.0,
        },
        "grass_rgb": (16, 58, 22),
        "infield_rgb": (22, 76, 30),
        "runoff_rgb": (34, 88, 38),
    },
    {
        "short_lt": "Barselona",
        "short_en": "Spain",
        "venue_lt": "Ispanija, Montmeló",
        "circuit_lt": "Circuit de Barcelona-Catalunya",
        "title_hud": "CIRCUIT DE BARCELONA-CATALUNYA",
        "subtitle_hud": "Montmeló — Spain",
        "air_c": 23,
        "track_c": 38,
        "race_laps": 66,
        "air_condition_lt": "Debesuota su pragiedruliais, sausa",
        "humidity_pct": 55,
        "wind_ms": "4–6",
        "wind_dir_lt": "Pietvakarių (nuo jūros)",
        "venue_en": "Barcelona, Spain (Montmeló)",
        "circuit_en": "Circuit de Barcelona-Catalunya",
        "air_condition_en": "Mostly dry, partly cloudy Mediterranean spring",
        "wind_dir_en": "Southwest (sea breeze)",
        "weather_lines_lt": [
            "Viduržemio pavasaris: daugiausia sausa, debesuota su pragiedruliais.",
            "Oro drėgmė ~55 %, vėjas ~5 m/s nuo jūros.",
            "Trasos paviršius šiltas, bet ne „įkaitęs“ kaip tropikuose.",
        ],
        "track_transform": {
            "scale_x": 0.92,
            "scale_y": 1.08,
            "shift_x": 0.02,
            "shift_y": -0.02,
            "rotate_deg": 8.0,
        },
        "grass_rgb": (22, 68, 28),
        "infield_rgb": (28, 88, 36),
    },
    {
        "short_lt": "Bakas",
        "short_en": "Azerbaijan",
        "venue_lt": "Azerbaidžanas, Baku",
        "circuit_lt": "Baku City Circuit",
        "title_hud": "BAKU CITY CIRCUIT",
        "subtitle_hud": "Baku — Azerbaijan",
        "air_c": 26,
        "track_c": 44,
        "race_laps": 51,
        "air_condition_lt": "Debesuota, dulkėta, gūsingas vėjas",
        "humidity_pct": 60,
        "wind_ms": "8–12",
        "wind_dir_lt": "Vakarų–šiaurės vakarų (Kaspijas)",
        "venue_en": "Baku, Azerbaijan",
        "circuit_en": "Baku City Circuit",
        "air_condition_en": "Caspian coast, gusty wind, dusty cloud cover",
        "wind_dir_en": "West–northwest",
        "weather_lines_lt": [
            "Kaspijos pakrantė: gūsingas vėjas ~8–12 m/s, dulkėtas debesuotumas.",
            "Drėgmė vidutinė ~60 %, trumpalaikio lietaus tikimybė ~15 %.",
            "Miesto trasoje — skirtingi asfalto sukibimo ruožai.",
        ],
        "track_transform": {
            "scale_x": 1.08,
            "scale_y": 0.9,
            "shift_x": -0.03,
            "shift_y": 0.03,
            "rotate_deg": -12.0,
        },
        "grass_rgb": (16, 58, 22),
        "infield_rgb": (22, 72, 30),
    },
    {
        "short_lt": "Singapūras",
        "short_en": "Singapore",
        "venue_lt": "Singapūras (naktinės lenktynės)",
        "circuit_lt": "Marina Bay Street Circuit",
        "title_hud": "MARINA BAY STREET CIRCUIT",
        "subtitle_hud": "Singapore — Night race",
        "air_c": 29,
        "track_c": 35,
        "race_laps": 62,
        "air_condition_lt": "Naktis, drėgna tropinė, perkūnijų rizika",
        "humidity_pct": 85,
        "wind_ms": "2–4",
        "wind_dir_lt": "Pietryčių (monsooninis)",
        "venue_en": "Singapore (night race)",
        "circuit_en": "Marina Bay Street Circuit",
        "air_condition_en": "Tropical night, very humid, shower risk",
        "wind_dir_en": "Southeast (monsoonal)",
        "weather_lines_lt": [
            "Tropinė naktis: labai drėgna (~85 %), karšta (~29 °C), bet be tiesioginių saulės spindulių.",
            "Trumpų liūčių / perkūnijos tikimybė ~45 % (lokalūs lietaus langeliai).",
            "Miesto canyon efektas — silpnesnis vėdinimas, danga greitai atvėsta po lietaus.",
        ],
        "track_transform": {
            "scale_x": 0.88,
            "scale_y": 1.1,
            "shift_x": 0.04,
            "shift_y": 0.01,
            "rotate_deg": 22.0,
        },
        "grass_rgb": (12, 48, 20),
        "infield_rgb": (18, 62, 26),
    },
    {
        "short_lt": "JAV (COTA)",
        "short_en": "USA",
        "venue_lt": "JAV, Ostinas, Teksasas",
        "circuit_lt": "Circuit of The Americas",
        "title_hud": "CIRCUIT OF THE AMERICAS",
        "subtitle_hud": "Austin — USA",
        "air_c": 24,
        "track_c": 41,
        "race_laps": 56,
        "air_condition_lt": "Giedra arba debesuota, vakarinė perkūnija galima",
        "humidity_pct": 45,
        "wind_ms": "8–11",
        "wind_dir_lt": "Pietų (Mexiko įlanka)",
        "venue_en": "Austin, Texas, USA",
        "circuit_en": "Circuit of The Americas",
        "air_condition_en": "Autumn Texas, dry to late-day thunderstorms possible",
        "wind_dir_en": "South (Gulf influence)",
        "weather_lines_lt": [
            "Rudeninis Teksasas: sausa arba trumpa perkūnija vakare (~25 % lietaus).",
            "Vėjas gūsingas ~10 m/s, žemas santykinis drėgnis ~45 %.",
            "Kalvų trasoje — dideli aukščio skirtumai, skirtinga dangos temperatūra posūkiuose.",
        ],
        "track_transform": {
            "scale_x": 1.05,
            "scale_y": 0.95,
            "shift_x": -0.02,
            "shift_y": 0.02,
            "rotate_deg": 15.0,
        },
        "grass_rgb": (20, 64, 26),
        "infield_rgb": (26, 82, 34),
    },
    {
        "short_lt": "Vokietija",
        "short_en": "Germany",
        "venue_lt": "Vokietija, Niurburgas",
        "circuit_lt": "Nürburgring GP",
        "title_hud": "NURBURGRING",
        "subtitle_hud": "Nürburg — Germany",
        "air_c": 17,
        "track_c": 22,
        "race_laps": 60,
        "air_condition_lt": "Debesuota, vėsoka, mišrių debesų sluoksnis",
        "humidity_pct": 70,
        "wind_ms": "3–6",
        "wind_dir_lt": "Vakarų (Atlantas)",
        "venue_en": "Nürburg, Germany",
        "circuit_en": "Nürburgring GP layout",
        "air_condition_en": "Cool mixed Atlantic weather, patchy rain possible",
        "wind_dir_en": "West (Atlantic)",
        "weather_lines_lt": [
            "Vidutinio platumos mišrus oras: debesuota, vėsoka (~17 °C), danga vėsi.",
            "Lietaus tikimybė ~35 % (lokalūs lietaus frontai Eifelyje).",
            "Drėgmė ~70 %, silpnas vėjas — rūkas arba dulksna ryte įmanoma.",
        ],
        "track_transform": {
            "scale_x": 1.0,
            "scale_y": 1.0,
            "shift_x": 0.0,
            "shift_y": -0.03,
            "rotate_deg": -6.0,
        },
        "grass_rgb": (26, 72, 32),
        "infield_rgb": (32, 92, 40),
    },
    {
        "short_lt": "Australija",
        "short_en": "Australia",
        "venue_lt": "Australija, Melburnas",
        "circuit_lt": "Albert Park Circuit",
        "title_hud": "ALBERT PARK CIRCUIT",
        "subtitle_hud": "Melbourne — Australia",
        "air_c": 22,
        "track_c": 36,
        "race_laps": 58,
        "air_condition_lt": "Kintanti: debesuota / pragiedruliai, lietus galimas",
        "humidity_pct": 62,
        "wind_ms": "12–16",
        "wind_dir_lt": "Pietų (Baso sąsiauris)",
        "venue_en": "Melbourne, Australia",
        "circuit_en": "Albert Park Circuit",
        "air_condition_en": "Changeable spring, gusty maritime winds",
        "wind_dir_en": "South (Bass Strait)",
        "weather_lines_lt": [
            "Kaitrų pavasaris: „keturi sezonai per dieną“ — debesys keičiasi greitai.",
            "Temperatūra ~22 °C, lietaus tikimybė ~30 %, vėjas ~15 m/s nuo jūros.",
            "Parko trasoje — daug smėlio ant trasos po lietaus.",
        ],
        "track_transform": {
            "scale_x": 0.96,
            "scale_y": 1.04,
            "shift_x": 0.03,
            "shift_y": -0.01,
            "rotate_deg": -18.0,
        },
        "grass_rgb": (24, 70, 30),
        "infield_rgb": (30, 90, 38),
    },
    {
        "short_lt": "Monakas",
        "short_en": "Monaco",
        "venue_lt": "Monakas, Monte Karlas",
        "circuit_lt": "Circuit de Monaco",
        "title_hud": "CIRCUIT DE MONACO",
        "subtitle_hud": "Monte Carlo — Monaco",
        "air_c": 21,
        "track_c": 34,
        "race_laps": 78,
        "air_condition_lt": "Debesuota su pragiedruliais, švelniai drėgna",
        "humidity_pct": 65,
        "wind_ms": "1–3",
        "wind_dir_lt": "Pietryčių (Viduržemio jūra)",
        "venue_en": "Monte Carlo, Monaco",
        "circuit_en": "Circuit de Monaco",
        "air_condition_en": "Mild maritime, partly cloudy, light rain chance",
        "wind_dir_en": "Southeast (Mediterranean)",
        "weather_lines_lt": [
            "Viduržemis prie jūros: švelni drėgmė ~65 %, debesuota su pragiedruliais.",
            "Lietaus tikimybė nedidelė ~20 %, bet siaurose gatvėse bet koks lietus drastiškai keičia sąlygas.",
            "Vėjas silpnas (~2 m/s), miesto šiluminis efektas.",
        ],
        "track_transform": {
            "scale_x": 1.12,
            "scale_y": 0.85,
            "shift_x": 0.0,
            "shift_y": 0.04,
            "rotate_deg": 35.0,
        },
        "grass_rgb": (14, 52, 22),
        "infield_rgb": (20, 68, 28),
    },
    {
        "short_lt": "Abu Dabis",
        "short_en": "Abu Dhabi",
        "venue_lt": "JAE, Yas sala",
        "circuit_lt": "Yas Marina Circuit",
        "title_hud": "YAS MARINA CIRCUIT",
        "subtitle_hud": "Abu Dhabi — UAE",
        "air_c": 29,
        "track_c": 31,
        "race_laps": 58,
        "air_condition_lt": "Sutemos, sausa, lengvas jūrinis drėgnis",
        "humidity_pct": 55,
        "wind_ms": "5–7",
        "wind_dir_lt": "Šiaurės vakarų (Persijos įlanka)",
        "venue_en": "Yas Island, Abu Dhabi, UAE",
        "circuit_en": "Yas Marina Circuit",
        "air_condition_en": "Dusk / evening, dry desert, light sea humidity",
        "wind_dir_en": "Northwest (Persian Gulf)",
        "weather_lines_lt": [
            "Vakarinis / sutemų etapas: labai maža lietaus tikimybė (<5 %), sausa dykuma.",
            "Oras ~29 °C, drėgmė ~55 % (jūros artumas), vėjas ~6 m/s.",
            "Danga greitai atvėsta po saulelydžio — skirtingas sukibimas posūkiuose.",
        ],
        "track_transform": {
            "scale_x": 0.9,
            "scale_y": 1.06,
            "shift_x": -0.01,
            "shift_y": -0.02,
            "rotate_deg": 5.0,
        },
        "grass_rgb": (16, 56, 20),
        "infield_rgb": (22, 74, 28),
    },
]
